name: "main"

on: ["workflow_dispatch", "push"]

jobs:
  changes:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3.5.1"
      - run: "echo 'The success of this trivial job enables automerging bot PRs.'"
