name: "main"

on: ["workflow_dispatch", "push"]

jobs:
  changes:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.1.0"
      - run: "echo 'The success of this trivial job enables automerging bot PRs.'"
